apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  annotations:
    che.eclipse.org/components-update-policy: managed
    che.eclipse.org/plugin-registry-url: {{ .Values.devworkspacetemplate.devfile }}
  name: {{ .Values.devworkspacetemplate.name }}
spec:
  commands:
  - apply:
      component: che-code-injector
    id: init-container-command
  - exec:
      commandLine: nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt
        2>&1 &
      component: che-code-runtime-description
    id: init-che-code-command
  components:
  - container:
      command:
      - /entrypoint-init-container.sh
      cpuLimit: 500m
      cpuRequest: 30m
      env:
      - name: CHE_DASHBOARD_URL
        value: https://devspaces.{{ .Values.deployer.domain }}
      - name: CHE_PLUGIN_REGISTRY_URL
        value: https://devspaces.{{ .Values.deployer.domain }}/plugin-registry/v3
      - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
        value: http://plugin-registry.openshift-devspaces.svc:8080/v3
      - name: CLUSTER_CONSOLE_URL
        value: https://console-openshift-console.{{ .Values.deployer.domain }}
      - name: CLUSTER_CONSOLE_TITLE
        value: OpenShift console
      - name: OPENVSX_REGISTRY_URL
        value: ""
      image: {{ .Values.devworkspacetemplate.codeImage }}
      memoryLimit: 256Mi
      memoryRequest: 32Mi
      sourceMapping: /projects
      volumeMounts:
      - name: checode
        path: /checode
    name: che-code-injector
  - attributes:
      app.kubernetes.io/component: che-code-runtime
      app.kubernetes.io/part-of: che-code.eclipse.org
      controller.devfile.io/container-contribution: true
    container:
      cpuLimit: 500m
      cpuRequest: 30m
      endpoints:
      - attributes:
          cookiesAuthEnabled: true
          discoverable: false
          type: main
          urlRewriteSupported: true
        exposure: public
        name: che-code
        protocol: https
        secure: true
        targetPort: 3100
      - attributes:
          discoverable: false
          urlRewriteSupported: false
        exposure: public
        name: code-redirect-1
        protocol: https
        targetPort: 13131
      - attributes:
          discoverable: false
          urlRewriteSupported: false
        exposure: public
        name: code-redirect-2
        protocol: https
        targetPort: 13132
      - attributes:
          discoverable: false
          urlRewriteSupported: false
        exposure: public
        name: code-redirect-3
        protocol: https
        targetPort: 13133
      env:
      - name: CHE_DASHBOARD_URL
        value: https://devspaces.{{ .Values.deployer.domain }}
      - name: CHE_PLUGIN_REGISTRY_URL
        value: https://devspaces.{{ .Values.deployer.domain }}/plugin-registry/v3
      - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
        value: http://plugin-registry.openshift-devspaces.svc:8080/v3
      - name: CLUSTER_CONSOLE_URL
        value: https://console-openshift-console.{{ .Values.deployer.domain }}
      - name: CLUSTER_CONSOLE_TITLE
        value: OpenShift console
      - name: OPENVSX_REGISTRY_URL
        value: ""
      image: {{ (index .Values.devworkspace.components 0).container.image }}
      memoryLimit: 1024Mi
      memoryRequest: 256Mi
      sourceMapping: /projects
      volumeMounts:
      - name: checode
        path: /checode
    name: che-code-runtime-description
  - name: checode
  events:
    postStart:
    - init-che-code-command
    preStart:
    - init-container-command
