apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-kuadrant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-kuadrant-kuadrant-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuadrants.kuadrant.io-v1beta1-admin
subjects:
  - kind: ServiceAccount
    name: create-kuadrant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-kuadrant-olm-view
  namespace: openshift-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregate-olm-view
subjects:
  - kind: ServiceAccount
    name: create-kuadrant
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-kuadrant-script
data:
{{ tpl (.Files.Glob "files/*").AsConfig $ | indent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-kuadrant
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 6
  template:
    spec:
      serviceAccountName: create-kuadrant
      restartPolicy: Never
      containers:
        - name: create-kuadrant
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          workingDir: /app
          command: ["/app/create-kuadrant.sh"]
          args: []
          volumeMounts:
            - name: create-kuadrant-script
              mountPath: /app
      volumes:
        - name: create-kuadrant-script
          configMap:
            name: create-kuadrant-script
            defaultMode: 493
